### ISSUE TITLE
Data driving it ?

### ISSUE THREAD

**Issue by gedw99** [Godotcam/goCamOpenSource#1]
It got my age wrong by 3 years . Still not bad.

the data is here : https://github.com/Godotcam/goCamOpenSource/blob/main/app/frontend/static/js/app/avs.js

I reckon that it maybe needs more data granularity to get better ?

**Comment by Godotcam** [comment]
Your message has been received by our support team. You will be answered soon.
If you wish to add further information, use the reply function of your mail agent and do not change the subjet.

Best regards

------------------------

Go.cam support team

**Comment by gedw99** [comment]
Thanksc
